#!/bin/bash

if [ -f /etc/shadow ]; then
	echo "Shadow password are enabled."
		if [ -w /etc/shadow ]; then
			echo "You have permissions to edit /etc/shadow!"
		fi
else
	echo "/etc/shadow file does not exits."
fi
